### ISSUE TITLE
Vote #6 does not load

### ISSUE THREAD

**Issue by NotFury** [ItsAZZA/buildcraftia#10]
Whenever I intend to vote on Vote #6, I am greeted by an Error 522 loading page. I understand this is a third party voting website, but possibly something can be done about it?

To reproduce this issue, either go https://craft-list.net/minecraft-server/BuildCraftia/vote or vote through the "Vote #6" link provided by /vote in game. 

![9267c3a002fb367e6e76d222b5a27d18](https://user-images.githubusercontent.com/48838422/54842288-28cff200-4c97-11e9-8d1f-ea4986982005.png)

**Comment by ItsAZZA** [comment]
Must be a temporary outage. Has been working for me the past week totally fine.
