### ISSUE TITLE
Lighting removal command is unknown by the server, after being suggested by it

### ISSUE THREAD

**Issue by NotFury** [ItsAZZA/buildcraftia#11]
A command was offered to remove lighting when I was world editing on World's realm; "//replace #brightness:1:15 0".
Upon trying this command, I was given "Unknown mask: #brightness:1:15 See: //masks 

**To Reproduce**
1. //paste an object multiple times until the suggestion comes up.
2. Attempt using "//replace #brightness:1:15 0"
3. Receive an unknown mask response by the server.

Screenshots:
https://gyazo.com/54dcf3f530b642a8969af795e0cab6f5
https://gyazo.com/08e5d57dfaf7d783d14f1db591ca5fe2

**Comment by ItsAZZA** [comment]
That's not the right way to use that particular pattern. You need to use `//replace #brightness[min][max] air` and it will replace all blocks with light level between min and max with air. You need to use brackets with all the arguments for masks and patterns.
