### ISSUE TITLE
Allow players to buy Creative Warps

### ISSUE THREAD

**Issue by knewnie** [ItsAZZA/buildcraftia#15]
Similar to the system in survival, players could be able to buy warps in the creative world with fish. Perhaps make it a little more expensive, but not by much. This would incentivize players to 1. Play on creative more 2. Build bigger and better builds and 3. Vote more.

**Comment by ItsAZZA** [comment]
I'll start working on this feature soon-ish™. Here are the steps so far.
- [x] Replace the Essentials warp feature with a Polarbear one
- [x] Create separate sections for server warps and player warps
- [x] Transfer existing warps to the new system
- [x] Testing and bug fixing
- [x] Release
- [ ] Warp categories (build style, size... e.g. medieval, modern...)

**Comment by ItsAZZA** [comment]
Added!
