### ISSUE TITLE
voting "rank" and percs

### ISSUE THREAD

**Issue by knewnie** [ItsAZZA/buildcraftia#18]
To get more people to vote, it might be interesting to, when a player hits a certain amount of rep (maybe like 150) they get a special "rank." their color would stay the same, but their name could be italicized or underlined, however i prefer italicized. a bonus of this rank could be a special join message similar to the ones penguins have. 
![image](https://user-images.githubusercontent.com/49075534/55520969-971b9980-5633-11e9-8956-2395090c059e.png)

other perks could be added, but the chat flair is the main thing i was thinking of. everyone loves looking cool in chat.

**Comment by ItsAZZA** [comment]
Yes, we could do something with chat. We've been thinking about giving players a custom prefix in chat. This would add something like `[V]` before their name. The italicizing might make names harder to read, plus, in my opinion, mixing italicized and regular names looks too busy in chat.

The join messages might get spammy, especially when there are a lot of players joining and switching servers.
