### ISSUE TITLE
the tip "lazycut is safer" isnt disabled when you use /tips on my realm

### ISSUE THREAD

**Issue by knewnie** [ItsAZZA/buildcraftia#20]
![2019-04-12_10 17 43](https://user-images.githubusercontent.com/49075534/56055069-6f9c8f00-5d0d-11e9-9797-f6d7f5906847.png)

not to mention i still think its WRONG it doesnt go away and is highlighted in a different color than the other tips, as if taunting me. please go away, i dont want you here.

**Comment by ItsAZZA** [comment]
Changed message settings. Issue fixed.
