### ISSUE TITLE
All armor stands are gone. 1.13

### ISSUE THREAD

**Issue by knewnie** [ItsAZZA/buildcraftia#23]
When creative updated to 1.13, all armor stands were deleted. This is kinda annoying for most people who have to replace them, but its ESPECIALLY BAD for spawn. most of the player armor stand easter eggs have been deleted, and this removes a lot of character and community charm from the spawn. I doubt there's a way to get them back, but if there is that'd be cool. I'm not counting on it. We should have players, if they can, remember where their armor stand was, and replace it. If they can't, they/staff should decide where to put it. I believe this problem also gets rid of the floating text that like tells new players where to go.

also in trying to inspect this issue i've realized there's no command to get to spawn yet, but that's possibly an issue with CH? unsure. thought it was worth reporting

**Comment by ItsAZZA** [comment]
I still see armorstands in spawn. I don't know why they would be removed all of a sudden. But unfortunately, at least I don't know of a way to get them back.

Spawn now has a command!

**Comment by ItsAZZA** [comment]
Unless there's any other information, unfortunately we're not able to get the lost armorstands back. The Armorstand Tools (AST) is now installed. Closing issue.
