### ISSUE TITLE
Custom Potion Menu

### ISSUE THREAD

**Issue by ItsAZZA** [ItsAZZA/buildcraftia#6]
**Description**: 
Custom potion menu for potion effects which lets players choose the duration and level for the potion. This new addition will also let players have truly infinite potion effects that are re-applied on death and server restarts. Drinking milk won't reset the effect either.

- [X] Create a custom menu for potion effects
- [X] Create submenus where players can change the effects, duration and level
- [x] Create a system that gives players potion effects based on their selections
- [x] Make sure players can't cancel permanent effects by dying, relogging or drinking milk
- [x] Create a command which can change effects from commandblocks or via a player run command
- [x] Create custom messages and help
- [x] Testing and bug fixing
- [x] Release

**Comment by RealMcGrew** [comment]
I'm excited for this feature to be added!

**Comment by ItsAZZA** [comment]
Functionality added to Polarbear. Testing and bug fixing can begin.
